### PR TITLE
Fix Cubic Spline tangent

### PR DESCRIPTION
**Pull request by takahirox**
This PR fixes Cubic Spline tangent.

In glTF  cubic Hermite spline form `m0` and `m1` are `(tk+1 - tk)bk` and  `(tk+1 - tk)ak+1` respectively but #40 and https://github.com/KhronosGroup/glTF-Sample-Models/issues/96#issuecomment-315213054 have missed `(tk+1 - tk)`.

glTF specification:
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation

Relative thread in Three.js:
https://github.com/mrdoob/three.js/pull/12907

### CODE REVIEW

**Comment by donmccurdy** [comment]
The results look right here, but one minor thing. The values of the track with custom tangents are:

```
[0, 28.91799545288086, 0, 0, 0, -6, 0, 15.24751091003418, 0, 0, 11.786787033081055, 0, 0, 3, -6, 0, 9.142221450805664, 0, 0, 0, 0, 0, 3, -6, 0, 0, 0 ]
```

but from the glTF spec:

> Implementation Note: The first in-tangent a1 and last out-tangent bn should be zeros as they are not used in the spline calculations.

**Comment by takahirox** [comment]
Yeah, I'm aware of that but I didn't touch them so far because they aren't used.
But I'll update to set zeros. It'd good time to fix now.

**Comment by takahirox** [comment]
Updated

**Review by donmccurdy — APPROVED** [review]
Tested and working in three.js.

**Comment by donmccurdy** [comment]
@bghgary is it possible to test this in BabylonJS? Looks good from my side, hoping to get a sanity check from a second engine but we could probably merge if that's not easy to do.

**Comment by bghgary** [comment]
Sure, BabylonJS has supported cubic splines for a while now. Is there an asset I should try?

**Comment by donmccurdy** [comment]
Oops, yes — this should be it: [InterpolationComparison.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1628761/InterpolationComparison.zip)

**Comment by donmccurdy** [comment]
Expected outcome shown here: https://github.com/mrdoob/three.js/pull/12907

**Comment by donmccurdy** [comment]
Awesome! When I tested i ran into https://github.com/BabylonJS/Babylon.js/issues/3478 and didn't get further, great that's fixed now. 😁

**Comment by takahirox** [comment]
Is InterpolationComparison.zip you posted above exported via blender with this fix?

**Comment by donmccurdy** [comment]
I believe so, it’s been a week so not impossible I got the wrong one.. looked ok in both engines.

**Comment by takahirox** [comment]
OK. I wanted to confirm just in case.

**Comment by donmccurdy** [comment]
Thanks! 🙂

**Pull request merged**
