### PR TITLE
export of Pointerproperties

### PR DESCRIPTION
**Pull request by IARI**
fix KhronosGroup/glTF-Blender-Exporter#238
export with extra-properties doesn't fail when the object contains Pointerproperties

### CODE REVIEW

**Comment by emackey** [comment]
Thanks @IARI.  What's the easiest way to create a PointerProperty to test this?

**Comment by IARI** [comment]
@emackey take this file:

https://gist.github.com/IARI/95d71a08fc767eb166023f3128ff90ec

put it in your blender addon folder, start blender, enable the addon:
image


The addon adds a PointerProperty to every object.
You can view and edit its value from the sidepanel (hotkey "N") in a View3D Region:
image

**Comment by IARI** [comment]
I have tested my PR myself and noticed that it works with Nested PointerProperties (part of a `PropertyGroup` which itsself is referenced by a `PointerProperty`), but does not work, when the object holds a `PointerProperty` directly.
In the latter case, the Pointerproperty will simpl be ignored but not be serialized.

**Reason:** 
See https://github.com/IARI/glTF-Blender-Exporter/blob/master/scripts/addons/io_scene_gltf2/gltf2_create.py#L450
* If an object has a PointerProperties of a `Propertygroup` type, it will be stored as python in an object that has a `to_dict` method, and the exporter runs the modified `JSONEncoder` on it.
* If an object has a PointerProperties of type `bpy.types.Object`, instead the object instance itsself (i.e. '<bpy_struct, Object("Lamp")>') has no `to_dict()` method

This isn't as bad as before: without the PR, the extra properties will not be exported, as the JSONEncoder fails. With the PR in this case, the property so far just will be ignored. I will however improve the PR such that both scenarois are considered.

**Comment by IARI** [comment]
@emackey Is there anything I can do to help here at this point?

**Comment by donmccurdy** [comment]
I'm not familiar with PointerProperties or PropertyGroups, so for my understanding, at a high level how can this be used? I think the gist is that objects/meshes/materials in the your scene might have a custom property pointing to other objects/meshes/materials in the scene, and so instead of JSON-encoding those objects you just return their names?

**Comment by IARI** [comment]
I don't know if it makes sence for may people, but I can quickly and abstractly describe our use case:
We use Threejs to render an interactive gltf scene.
Some sufficiently complex tree/graph structures contains nodes correspond to 3D objects and edges that reference these objects. We use PropertyGroups and PointerProperties in a Blender addon to allow the configuration of this structure from within Blender.

**Comment by donmccurdy** [comment]
Ok, sounds good to me. Agreed that names make more sense than trying to JSON-encode the object itself here. I'd been thinking of suggesting use of the glTF node index instead, but (1) I don't know how an application like three.js use that, and (2) these references might be materials or meshes rather than nodes.

Given (2), would it make sense to put the name in a sub-object, like `{custom_pointer: {name: 'MyNode'}}`, so that later we can also add a `type` property to disambiguate materials, meshes, nodes, etc.? I don't know if Blender ensures unique names across types but glTF certainly does not. E.g. `{name: 'MyMaterial', type: 'MATERIAL'}`.

**Comment by IARI** [comment]
@donmccurdy 

Types that have names in Blender are subtypes of `ID` - see https://docs.blender.org/api/2.79/bpy.types.ID.html#bpy.types.ID

These names are unique in Blender per type domain 
but not across all types, for instance:
- you can have an `Object` named "foo" that uses data from a `Mesh` named "foo" and has a `Material` named "foo"
- you can have at most one instance of type T named "foo", for every T:`ID`  (i.e. `Object`, `Meshdata`, `Material`, ...)

Also consider the PointerProperty documentation:

https://docs.blender.org/api/2.79/bpy.props.html#bpy.props.PointerProperty

When you define a PointerProperty in Python, you have to specify a type which is either a subtype of 

1.  `ID` or
2. `PropertyGroup`

Case 1. is covered by this PR. consider the example from the gist linked above:

```python3
bpy.props.PointerProperty(type=bpy.types.Object, name="NestedPointer")
```

When you define a Property like this, it is clear at any time, that this Pointer can only have a value of type `Object` and hence the name is unique for this particular property.

The only hypothetical scenario I can imagine where the type would not be clear and thus the name not unique was, if you could specify a subclass of `ID` which itsself is inherited by multiple implementations - effectively haveing a PointerProperty referencing a sum-type.
However, I don't think there is any native class that does this, I don't think it is officially defined behavior or would be supported by PointerProperty - Probably you can not even define your own subclasses of ID in a way that works properly with Blender - I'm not an expert on the matter and might be wrong though. 
But I think it is safe to ignore this case for now.

Anyway, the approach you suggest also sounds safe to me and its no big deal to adapt my own implementation. 
Given the info in this post I'll wait on your decision on the matter, and in case you stick with the suggestion gladly implement it.

**Comment by emackey** [comment]
> would it make sense to put the name in a sub-object, like `{name: 'MyNode'}`

I like this idea too.

**Comment by donmccurdy** [comment]
Thanks @IARI — I think it would be safer to move the name into a sub-object, just in case we later want to serialize additional info from an object, e.g. the type, so that wouldn't break the previous behavior. But there is no need to write `"type": "object"` in this PR.

**Comment by IARI** [comment]
@donmccurdy, @emackey 

Implemented the requested change, including name and type parameter.
example output I got during testing:
```json
            "extras" : {
                "explore_world" : {
                    "clip_tree" : {
                        "name" : "MycoolTree",
                        "type" : "ClipNodeTree"
                    },
                    "transitions" : [
                        {
                            "goalNavState" : {
                                "name" : "Cube",
                                "type" : "Object"
                            },
                            "sourceNavState" : {}
                        }
                    ]
                }
            },
```

**Comment by donmccurdy** [comment]
Thanks @IARI!

**Pull request merged**
