### PR TITLE
Fixed Specular Node

### LINKED ISSUE #222: Specular Glossiness node is broken
Hello,

I've discovered that the "glTF Specular Glossiness" does not work correctly!

First, some basic assumptions I made based on the [extension specification](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md):
* The **specularFactor** property is an RGB property that colors the reflective portion of the shader.
* The **specularGlossinessTexture** is an RGBA texture property (RGB specular + A Gloss), which is mapped to the **Specular** and **Glossiness** properties in the node group
* A material with a zeroed **diffuseFactor** and/or **diffuseTexture** still has a reflective surface color matching the relevant specular properties noted above.

The node's present behavior is inconsistent with these assumptions!
* In Blender, an RGB value plugged into either **Specular** or **SpecularFactor** is interpreted as a black and white value.
* Zeroing the **Diffuse** and/or **DiffuseFactor** values, whilst a specular value is non-zero, still results in a black material.

Demonstrations follow:

demon_1

demon_2

demon_3

Further notes:
* The present behavior is also inconsistent with other glTF implementations (like [this one](https://bghgary.github.io/glTF/convert-between-workflows/))
* The present behavior, inconsistent with the assumptions, exists in both the glTF.blend and glTF2_Principled.blend variants of the node.
* Here are the .blend files I used to make the demonstration images: [demonstration.zip](https://github.com/KhronosGroup/glTF/files/2017096/demonstration.zip)

Information:
```
Commit: 8af23eb
Blender Version: 2.79b
```

Best Regards,
Sofus Rose

### PR DESCRIPTION
**Pull request by so-rose**
**Motivation** As per #222, the Specular Glossiness node is quite broken currently. I rebuilt it according to the specification, so it's fixed!
- Before, the results were correct given two really restrictive constraints: The Glossiness had to be 1.0, and the Specular had to be completely desaturated.
- The Principled variant had a completely broken Specular component; turning off Diffuse would render the shader completely black no matter what.

**Testing** Using this node, I compared exported results in https://sandbox.babylonjs.com to Cycles. They are comparable.

**Implementation Details** Here's how I implemented the fixes:
- I redid the Schlick Fresnel approximation, making it attenuate properly to Roughness.
    - I used Roughness as a factor to mix between Normal and Incoming, whose result is dot'ed with the Incoming vector.
- I now add the Diffuse & Glossy shaders, and enforce energy conservation by multiplying the final Diffuse color by the Specular color (before Fresnel), before it's plugged into the Diffuse shader.
- The Diffuse shader now gets a Roughness input too; the effect is negligible, but I'd rather be mathematically correct :)
- I kept the GGX micro facet model, since it approximates game engines quite well.
- Shader performance is technically ever so slightly slower, but negligibly in practice. My guess is that Roughness-attenuated Fresnel is the reason.
- I put the Occlusion step before energy conservation.

**Principled Conundrum** A real specular workflow is impossible, even in theory, to correctly implement using the Principled Shader new to Blender 2.79+. **As such, I have removed the Principled version of the Specular Glossiness Node, since it it broken and cannot be fixed - I propose that the user not even have the option to use a broken node**!
- The impossibility of this is, I believe, easy enough to prove: A conformant Specular shader is capable of different Diffuse and Specular color components at the same time, and the Principled Shader has no way to replicate that.
- It *is* possible to approximate a Specular workflow with the Principled Shader, *if* certain constraints are placed on that Specular workflow. However, in a sense, that's redefining the glTF Specular spec that this exporter tries to adhere to.
- As for backwards compatibility, shaders produced with the Principled Specular node right now are extremely misleading. The Cycles representation is simply not correct. **Still, I understand that this could be a blocker; I'm interested in your opinions and am happy to revert this change.**

**Other Changes** I also implemented a couple of nicities:
- Rebuilt the Specular node's interiors to be easier to look at & reason about.
- Removed subnodes that were imported along with with Specular node; it's now standalone.
- Wrote a longer README, including more detailed instructions & common pitfalls that would error-lessly prevent a material export.

Also, this closes #222.

### CODE REVIEW

**Comment by emackey** [comment]
Thanks @so-rose!  We'll take a few days to test this out.

**Comment by so-rose** [comment]
@emackey Cheers; was just wondering about the status of review on this?

**Comment by emackey** [comment]
Hi @so-rose.  I love the organizational look of the node groups here, very clean layout.

This is quite challenging to review as there is no way to diff the actual changes in behavior vs the older node groups.  I'm not sure how to detect potential breakage other than extensive testing with projects linked against the older groups (and my own projects all use append, not link, to avoid such problems). 
Still I do very much want to merge this, if we can construct adequate tests for it.

Any thoughts on how to proceed @donmccurdy or @UX3D-nopper?

**Comment by donmccurdy** [comment]
I agree with the changes proposed here, including removal of the Principled spec/gloss node. But I'm not confident I know how to review it adequately, either. Assuming https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scenes/04_sphere_specular_glossiness.blend works before and after this change, could we add another example that reproduces some of these fixed issues?

**Comment by so-rose** [comment]
@emackey @donmccurdy 

I can try to render permutations of settings with both nodes under controlled circumstances, thus making comparisons (in the vein of #222) that try to demonstrate the specific differences between old functionality and new (including those that were fixed, and how).

It is a difficult one to do in a more scientific way, I agree - do you think this is the correct approach?

**Comment by donmccurdy** [comment]
That sounds good to me, thanks :)

**Comment by donmccurdy** [comment]
@emackey what do we think about this, with current development on glTF-Blender-IO? I'm wondering if we should look for similar inputs on a non-functional `glTF Settings` or `glTF Export` node, and leave users to configure the rendered output using builtin nodes like the **Specular** node. But I wouldn't be opposed to putting this node in the new project, either.

**Comment by emackey** [comment]
Unfortunately, as much as I loved this node re-org, I think in the new project we should keep everyone focused on Principled BSDF.  An "Export" or Settings node group would only have options that can't be expressed any other way in Blender, and I think that's down to just the occlusion map now.

Sorry @so-rose, I really liked this but I think the whole idea of a custom node group is obsolete now.

**Pull request closed without merging**
