### PR TITLE
Fix object anim parent inverse

### PR DESCRIPTION
**Pull request by pjoe**
Parent inverse wasn't taking into account for object animation.

This PR adds handling of parent inverse for object animations.

__NOTE__: It doesn't attempt to handle cubic spline tangents

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks @pjoe! Would you mind adding a simple `.blend` file reproducing the issue?

**Comment by pjoe** [comment]
That is part of the PR in scenes/06_parent-inverse-anim.blend :)

**Comment by donmccurdy** [comment]
Oops, I see 😅  — that's perfect thanks. My only concern then is that the top-center cube is rotated to match its parent in the glTF asset, but not in the Blender scene:

| blender | three.js |
|---|---|
| screen shot 2018-03-21 at 9 00 40 pm  | screen shot 2018-03-21 at 9 01 38 pm |

babylonjs also matches the three.js screenshot.

**Comment by pjoe** [comment]
Hmm yeah that doesn't look quite right :S

I had debug prints in the exporter while testing that definitely showed the rotation quats being corrected, but I will take a look tomorrow (have a crazy deadline today).

**Comment by pjoe** [comment]
This is another issue, if you turn off convert Z up to Y up it works correctly.

So apparently rotation animation doesn't handle the Z up to Y up correctly :S

**Comment by pjoe** [comment]
After a bit more investigation, it's the applying of the parent-inverse for rotations that doesn't correctly work with the z-up to y-up conversion.

Looking into fixing ... if I can just make those damn quaternions 'do the right thing' (tm)

**Comment by pjoe** [comment]
Finally got this working :)

I also added quaternion and axis-angle rotation anims to the test file.

It now shows correctly in https://gltf-viewer.donmccurdy.com/

**Comment by donmccurdy** [comment]
Thanks! 🎊

**Pull request merged**
