### PR TITLE
Use uint16 as the smallest type for index buffers

### PR DESCRIPTION
**Pull request by klacansky**
Direct3D does support only uint16 and uint32 for index buffers and
some GPUs will give warning if uint8 is used. This requirement forces
a conversion before uploading the indices to device memory. Given
the small size of < 256 indices the use of uint16 is a negligible
overhead.

> **NOTE:** We are in the progress of merging this project into
[glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO), a combined importer/exporter.
In the future this repository (glTF-Blender-Exporter) will be archived, and issues and pull
requests closed. We recommend that new issues and pull requests be opened against glTF-Blender-IO, instead.

### CODE REVIEW

**Comment by klacansky** [comment]
Fixes #328

**Comment by lexaknyazev** [comment]
@donmccurdy Since this issue has been mentioned previously (https://github.com/KhronosGroup/glTF-Sample-Models/issues/187), should we open a spec issue to add an implementation note and possibly a validation hint? Btw, Metal also requires at least uint16.

**Comment by donmccurdy** [comment]
Sounds good; opened https://github.com/KhronosGroup/glTF/issues/1471.

**Comment by donmccurdy** [comment]
Thanks!

**Comment by donmccurdy** [comment]
Opened https://github.com/KhronosGroup/glTF-Blender-IO/pull/56.

**Comment by klacansky** [comment]
I appreciate you opened the spec issue and did the review.

**Pull request merged**
