### PR TITLE
Support multiple actions, NLA tracks

### LINKED ISSUE #150: Skeletal meshes + animation Actions support in the nearest future ?
I am wondering if this exporter will support skeletal meshes + animation Actions in the nearest future (for Blender 2.79).

Thanks beforehand

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #150, #118, #112, #39.

Tasks:
- [x] Export multiple animations based on actions used in NLA tracks
- [x] Support morph targets / shape keys.
- [x] Support "bake skinning" option.

Attempting to implement support for multiple actions. There seems to be no good way to detect which actions could actually affect an object, so instead I'm using NLA tracks for this purpose. This means you must select which actions to export, otherwise only the active action is used.

In the NLA editor, you must *Push Down* each action that should be exported. Using *Stash* might also work, I didn't test that. In order for the action to be listed, you must open the *Dope Sheet* and make that action active, first.

screen shot 2018-03-03 at 1 22 38 am

Once you've done that for each action, they should be listed regardless of whether any are active:

screen shot 2018-03-03 at 1 17 49 am

/cc @sketchpunk @motorsep @cdata @nicocornelis if you are able to test this, I'd appreciate it. 🙂

Updated exporter:  
[io_scene_gltf2.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2152073/io_scene_gltf2.zip)

@cdata this is similar to your approach from #111, I think, but I've (attempted to) export 1 glTF animation for 1 Blender action, rather than separate for each object. Not sure whether that is the right approach. There is also some extra work to handle caching now.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Definitely some bugs to iron out, but e.g. this character is animating correctly:
[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1777331/Archive.zip)

**Comment by motorsep** [comment]
Nice! Why not to just export all actions (each as an individual anim) and let user delete unnecessary ones upon importing glTF into UE4, for example? That's how it works with FBX right now.

**Comment by donmccurdy** [comment]
@motorsep Yeah, I expect we’ll need an export option or two in the end, e.g. if two characters share a “walk” action, are they intended to be played separately or together? Depends on context... But hopefully we can get something basic working first and unblock most workflows.

**Comment by motorsep** [comment]
@donmccurdy As a game dev I usually export one character at a time. Selected mesh + respective armature (or selected armature). Actions should be unique to each armature. 

It would be also a good idea to add prefix to exported anims. For example, you mesh (object) is called Char1. So you could export its Actions with prefix Char1_*. For example "walk" action as Char1_walk. I believe FBX exporter does that (or maybe UE4 does that on import, not sure).

**Comment by donmccurdy** [comment]
Makes sense. There’s not going to be a one size fits all solution here, since others may want a single “animation” that targets multiple objects in sync, so we’ll have to allow some options for sure. I think the default should probably not be `N actions * M meshes = N * M animations`, because that has led to some misunderstandings and bad loader implementations before. I’d like to have defaults that work reasonably well for runtime use, since users might not be editing this in an engine at all, and then add in more advanced options stuff from there.

Should also note, this PR uses NLA tracks _only_ as indications of which actions are active. NLA tracks composing multiple actions with transitions will need to be baked to a single strip and action to export correctly.

**Comment by motorsep** [comment]
What if animator doesn't use NLA at all? (I never do and I have no clue how I'd use it for the purpose of just exporting to glTF)

Also wondering why not to make a copy of the scene on export, bake everything, export and then discard temporary copy. That would allow animator to keep actual scene unbaked, providing nondestructive workflow (I believe we had that in Doom 3 md5 exporter)

**Comment by donmccurdy** [comment]
The main to do first is just getting this tested enough to find errors in the code, you only have to press “Push Down” on each action you want included with the character. We can figure out which options to add and perhaps do NLA track baking once something basic is in place.

**Comment by donmccurdy** [comment]
Added a ZIP with the updated exporter in the OP.

**Comment by emackey** [comment]
I tried adding a location change (2 animation keyframes) to the default Blender cube, clicking "push down" to make an NLA track, and got an error on export.  Did I miss a step?

```
  File "blender-2.79-windows64\2.79\scripts\addons\io_scene_gltf2\gltf2_animate.py", line 204, in animate_location
    joint_cache = export_settings['gltf_joint_cache'][action_name]
KeyError: 'CubeAction'
```

**Comment by donmccurdy** [comment]
@emackey Thanks — should be fixed now.

**Comment by inkthorne** [comment]
This is awesome, @donmccurdy! I had started looking into fixing this, too, after my comments on #39. I grabbed your .zip and tried it out with a simple scene. I know you're in just "getting it to work" mode, so some of these comments might be for the future:

Don't hate me, but I think you're going to want to keep the existing exporter behavior for `animations[0]` (i.e. if objects have an assigned action, those actions get exported into a single animation). It's ideal for things like Sketchfab, Facebook, and game cinematics where you want to play a single animation and have the whole scene animate. The separate animations would then only be exported from the NLAs of an object.

> I think the default should probably not be N actions * M meshes = N * M animations,

I completely agree, however, I think that only should apply at the `accessors[]` level. If the same action is assigned as an NLA to 2 or more objects, each object should have it's own `animations[]` entry with a duplicated `samplers[]` entry which references the same `accessors[]` entry. Currently, I'm getting all objects that have a 'Slide' NLA grouped into a single 'Slide' animation, so animating them separately would be difficult.

> It would be also a good idea to add prefix to exported anims. For example, you mesh (object) is called Char1. So you could export its Actions with prefix Char1_*. For example "walk" action as Char1_walk.

It's convenient for the exporter to output uniquely named animations, but there are some authoring drawbacks to this approach. Example, the door of a house is parented to a hinge. It's the hinge that needs the animation, but "hinge_open" isn't an ideal animation name compared to "door_open". My preference would be to export the animations with just the name of the action OR use the name of the NLA track if it has been changed from the default "NlaTrack"*. This way folks can specify what they want the animation called and if they want it to be uniquely named.

**Comment by donmccurdy** [comment]
For comparison, here are the settings exposed by the "Better COLLADA" exporter and FBX exporter:

**COLLADA**
- [ ] All actions (writes all actions for 1st armature found, to separate DAE files)
- [X] Skip (-noexp) actions (skip control actions)

**FBX**
- [X] NLA strips (export each non-muted NLA strip as AnimStack, if any, instead of global animation
- [X] Export each action as separated AnimStack, instead of global scene animation (some objects will get all actions compatible with them, others will get none at all)

These aren't perfect parallels, because both are exchange formats where it's pretty much assumed you're doing more processing in e.g. UE4, whereas glTF can be used for runtime, but it's a start. And of course there are options for baking keyframes but that's out of scope for this PR.

***

From various comments in this thread:

> If objects have an assigned action, those actions get exported into a single animation

> Why not to just export all actions (each as an individual anim) and let user delete unnecessary ones upon importing glTF into UE4, for example?

> My preference would be to export the animations with just the name of the action OR use the name of the NLA track if it has been changed from the default "NlaTrack"*.

...let me try to propose a couple of export scenarios / settings:

1. No NLA tracks are used, multiple actions are present. A single global animation is written, with each object moving according to its active action, if any. Good for cinematic case, e.g. Facebook.
2. No NLA tracks are used, multiple actions are present. Each action is exported as a separate animation for each object to which it could apply, e.g. `N * M` animations. Good for import into an engine where further editing happens, e.g. UE4.
3. NLA tracks are used. Each NLA track is exported as an animation, named according to the track name (if non-default) or `<object_name>_<action_name>` as fallback. If multiple NLA tracks share the same name, they are merged into a single glTF animation track. Good for runtime use, e.g. three.js or A-Frame, where we want to play different clips dynamically, without exporting bloated files.

Assuming those three cases are available by some combinations of settings and defaults, am I missing anything necessary?

**Comment by inkthorne** [comment]
For the use cases I'm aware of, those cover it.

> If multiple NLA tracks share the same name, they are merged into a single glTF animation track.

If that can be used to put an attacker's 'punch' action into the same animation as the defender's 'dodge' action, that is amazingly cool! :)

FWIW, I'm not a huge fan of **2**. It doesn't add export capability like **1** or **3**. It may offer a slightly nicer workflow in certain situations, but it also complicates the exporter (i.e. how robust does determining if an armature is compatible with an action need to be?). But, I might be overlooking something.

I like that **1** & **3** are compatible with each other, so no option toggle would be needed, things would 'just work'. I'm definitely interested in hearing others' opinions on this.

**Comment by inkthorne** [comment]
As a side-note:

Using **Stash** has some advantages over using **Push Down**. Both will create an NLA track with the given action, but **Stash** creates a locked & muted NLA track, so it won't affect your object's current animation by trying to combine with the current action or the other NLAs. It's also nice because, by definition, a stashed action is an unmodified, single-action NLA (which is all we will support exporting to begin with).

**Comment by inkthorne** [comment]
I'm sorry, @donmccurdy, for duplicating your work. I had already started on my own changes before seeing your tweet about this, and I just continued with it. If there's anything in this version of the exporter you'd like to take, please do.

The changes accommodate 1 & 3 from above:
- All the currently assigned actions of objects are combined into a single unnamed animation at animations[0]. This is how the exporter previously worked, so there's no change in behavior here.
- An object's NLA tracks are exported as additional named animations. If the NLA track has been renamed from the default, the animation name is the NLA track name. If the NLA track name has **not** been renamed from the default, the animation name is `<object_name>_<action_name>` in order to be unique.
- NLA tracks that have the same name are combined into a single animation with that name.

I've run some simple test cases for skinned & articulated scene, it also appears to successfully export the TwoAnimCharacter model as well. If you have time, I would be interested in hearing if it's behaving as you'd expect.

NLA exporter: [nla_export.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1799988/nla_export.zip)

**Comment by inkthorne** [comment]
@motorsep, the way the exporter currently works (exporting all currently assigned actions) into a single animation, is ideal for full-scene (cinematic) animations. This scenario is useful when you want to display an animated 3D scene in things like Sketchfab, Facebook, or even game cinematics. In these cases, you want to load up the scene and then just play a single animation that animates everything. In that case, every object is assigned an action that animates over the entire timeline period.

However, with the changes, additionally the single-action NLAs are exported as separate animations (i.e. run, walk, jump, attack, etc). You get a separate animation for each NLA (i.e. run @ animations[1], walk @ animations[2], etc). This is the scenario that us gamedevs are mainly interested in, because the animations are played & blended dynamically based on user input.

Did that answer your question? I think we might be tripping up over the Blender terminology.

**Comment by motorsep** [comment]
@inkthorne yep, makes sense. I am not sure why you refer to NLAs, since there is no point to even bother with NLA when working with individual Actions. I've animated and exported to numerous engines, starting with Quake 1 and ending with UE4 and I never even opened NLA Editor. Export add-ns would also grab Actions directly, never even touching NLA tracks.

**Comment by donmccurdy** [comment]
Thanks @inkthorne! More approaches to this are certainly welcome. :) From this snippet of your code...

<details> <summary> process_object_nlas() </summary>

```python
    def process_object_nlas(blender_object, nla_animations):
        """
        Iterate through all of the NLA tracks and make animations out of their actions.
        Append the newly created animations to 'nla_animations'.
        """
        if blender_object.animation_data is None:
            return

        nla_tracks = blender_object.animation_data.nla_tracks

        if nla_tracks is None:
            return

        for nla_track in nla_tracks:
            nla_channels = []
            strips = nla_track.strips

            if strips is not None and len(strips) == 1:
                strip = strips[0]
                blender_action = strip.action
                process_object_animation(blender_object, blender_action, nla_channels, samplers)

                if len(nla_channels) > 0:
                    # Use the NLA track name as the animation name, if it's been changed from the default.
                    if not nla_track.name.startswith("[Action Stash]") and not nla_track.name.startswith("NlaTrack"):
                        nla_animation_name = nla_track.name
                    # Otherwise, create a unique name for the animation from the object & action strip.
                    else:
                        nla_animation_name = blender_object.name + "_" + strip.name

                    # Attempt to find an animation with the same name.
                    nla_animation = None
                    for animation in nla_animations:
                        if animation['name'] == nla_animation_name:
                            nla_animation = animation
                            break

                    # Combine animations with the same name.
                    if nla_animation is not None:
                        nla_animation['channels'] = nla_animation['channels'] + nla_channels
                    # Otherwise, create a new animation.
                    else:
                        nla_animation = {
                            'channels': nla_channels,
                            'name': nla_animation_name,
                        }
                        nla_animations.append(nla_animation)
```

</details>
<br/>
<p>... it looks like what would happen is that if there are multiple actions sequentially in an NLA track, they'll all be written to the same glTF animation, but stacked on top of one another and starting at the same time. Am I misunderstanding, or do you know if there's a way around that? I think we can "bake" the NLA to an action and then export that, but it would be nice to avoid re-sampling if it's possible...</p>


<p>About single-action NLAs, it sounds like there's no reason to think of that as a special case. If someone wants a single-action clip they can stash it, or mark it active, or use an <b>All actions</b> option if/when we add that. And if they did make a single-action NLA it should "just work" anyway, as long as we handle complex NLAs right. So I'm not too worried about the distinction right now.</p>

**Comment by inkthorne** [comment]
> ... it looks like what would happen is that if there are multiple actions sequentially in an NLA track, they'll all be written to the same glTF animation, but stacked on top of one another and starting at the same time.

@donmccurdy, it shouldn't. The code only exports an NLA track if there's **only** a single strip and then only exports the `strips[0].action` as the animation. It seemed like a reasonable limitation for a 2 reasons:

1.) Blender NLA tracks are specific to the object they're assigned to and can't be reassigned or shared with other objects like Blender actions. While it's completely possible you might want to author a complex NLA that only that object uses, you're also limited to authoring that animation using a **single** NLA track.

2.) Complex animations are often put together not just by using multiple strips in a single NLA track, but by also combining **multiple** NLA tracks.  You can then bake these into a single action which can then be shared and used to animate other objects. This action can then be assigned as a stashed action (single-action NLA) for export.

That said, there may not be anything wrong with the exporter baking out a multi-strip NLA track as an animation (as long as it doesn't bake single-strip NLAs and make them unnecessarily larger). But, given **2** above, it wasn't needed to get things working. :)

**Comment by inkthorne** [comment]
> Export add-ons would also grab Actions directly, never even touching NLA tracks.

@motorsep, you're right; however, glTF doesn't currently support soft targets for animations. Each animation channel in glTF must be targeted to a specific node or bone by a (hard) index rather than a (soft) name. This means that in order for an action to be exported, it has to be specifically assigned to an object.

In a Blender file where you have a character and 3 actions: walk, run, & jump; only 1 of these actions can be assigned to your character at a time. In order to associate multiple animations with the character, the NLA tracks are used. Another way to deal with this would be to export all actions as if they were assigned to the first (or all) valid object(s). That works for simple scenes (e.g. a single character), but not for complex ones.

In either case, these strategies are just ways to give an exported glTF animation hard target(s). IMO, if an `animation.channel.target` could be a name OR an index, none of these work-arounds would be necessary. But, I realize changing the spec is a much bigger deal than changing the exporter. :)

**Comment by motorsep** [comment]
@inkthorne I still don't get the issue. Select Armature, select meshes and export. Export one Action for selected Armature at a time. Like I mentioned in the past, none of the exporters I used had any issues with multiple Actions. For example, you can see what Doom 3 skel/anim exporter does: https://github.com/motorsep/blender-idtech4-md5 (I didn't code that beast, only did some tweaks)

Also worth mentioning that if you have multiple Armatures in your scene, whether it's a cinematic anim or anims for AI-driven characters, you still want to export one Armature at a time and then assemble it in the game engine of your choice.

Since glTF was never meant to be an exchange format as FBX or COLLADA, I don't see why one would want to have multiple armatures inside glTF scene.

**Comment by donmccurdy** [comment]
> The code only exports an NLA track if there's only a single strip and then only exports the strips[0].action as the animation.

@inkthorne Ah that makes sense, thanks!

> Export one Action for selected Armature at a time  ... export one Armature at a time ... and then assemble multiple glTF scenes/files into one scene in the game engine of your choice.

@motorsep For my use case, the glTF file is for last-mile transmission to a WebGL application running in a user's browser. There is no easy way to assemble different actions into a single animation later, and having any unused actions attached to an Armature means unnecessary file size for end-users. The expectation of exporting one armature at a time is (usually) fine, the entire scene does not need to be in one file.

There's no need to pick and choose workflows, I think we can support what everyone is describing here... just trying to clarify some of the use cases. I still think options (1), (2), and (3) from https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166#issuecomment-370330190 would accommodate this, but let me know if I've missed something.

**Comment by pjcozzi** [comment]
@donmccurdy anything you need here to bump this along?

**Comment by NoxWings** [comment]
Just to reanimate the discussion I like to give some feedback. I like the 3 options proposed by @donmccurdy.

About the 2nd option: 
This is how I would have expected the exporter to work by default since my workflow also involves a single character per blend file. 

About the 3rd option:
BUT after learning about the difference of how blender doesn't really link actions with  armatures and how the gltf spec needs a "hard" link, I really like the idea about exporting non-muted NLA tracks. It just looks like THE CORRECT CHOICE now.

But the first time I read it I just thought "why would I have to tinker with the NLA editor (3)? I just want all my actions exported (2)". So I consider having option (2) too would add value to the proposition too.

**Comment by dantoye** [comment]
It took me hours of debugging to end up here and I'm so glad you're working on this. 

I'll be experimenting with this brand soon, but my vote is that all NLA tracks be exported as animations *as well* as all Actions. animations[0] should be the assigned Action (if present), followed by all actions, followed by NLA tracks if possible.

**Comment by NoxWings** [comment]
I'm perfectly fine with this. I'm currently using this branch for my project without problems.

**Comment by donmccurdy** [comment]
I think this PR is pretty close now, what's missing currently is support for the "bake skinning" option. I haven't tested it, but it probably needs some changes to do anything meaningful with actions and NLAs. Unfortunately I haven't had time lately to make more progress on this.

**Comment by donmccurdy** [comment]
The "bake skinning" option is now working. Status:

1. [x] Actions that are active, stashed, or used by NLAs are exported as glTF animations.
2. [ ] Add option to include Actions that are not used or referenced.
3. [ ] Full NLAs are exported as a whole (not just their individual actions).
4. [ ] NLAs are merged when they share the same name.

I don't think 2-3 need to block this PR being merged, but they are nice additions for later. If this looks correct and stable so far, I'd like to get this merged before adding more features.

**Comment by donmccurdy** [comment]
Hm, with current changes the Polly model does not export quite correctly:

screen shot 2018-04-22 at 2 46 54 pm

screen shot 2018-04-22 at 2 47 50 pm

It looks like bones that are not children of the root bone for an armature become offset. This can be fixed by re-parenting the bones, but needs a bit more work I guess...

**Comment by motorsep** [comment]
Btw, would it be possible to export only bone hierarchy (as an option) ? 

I recall when exporting into FBX, Armature becomes root bone and actual root bone becomes its child. I am sure there are use cases when you need to keep Armature as root in the export, but generally hierarchy should only include bones.

**Comment by donmccurdy** [comment]
@motorsep Could you open a new issue? And to clarify, do you mean in this scenario:

```
scene
├── mesh
└──armature
  └── root
    ├── shoulder.l
    ├── shoulder.r
    ├── ...
    └──  head

```

... have an option to omit the armature and use `root` as the root of the skeleton?

**Comment by AndrewTziAnChan** [comment]
I have a simple character animation with skeletal animation and blend keys. When I export the animation, I expect that the animation keeps the integrity of the skeletal animation with the blend keys.

I tried a few of the glTF viewers, but none of them seemed to preserve the blend key animation following import. I'm not sure if the file is missing the blend key animation or if the importers and viewers simply are not yet ready for animation blend shape animation.

Here's the animation in Blender.

9c8a792222456724a1931a548ca28480

Here's what I see using https://gltf-viewer.donmccurdy.com/

c3f10f35adca69eb13398e79f43f3bdd

The shape keys are present, but they're not being animated in sync with the skeletal animation. Instead, the shapes are statically initialized to the blend value of the first key of the animation.

What's the best way to visually inspect that animations are exported correctly?

Here's the blend file if useful:

[Cloud-glTF.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2011542/Cloud-glTF.zip)

**Comment by donmccurdy** [comment]
@AndrewTziAnChan thank you for the example – I've fixed that issue in this PR. There is now a separate animation entry for the morph targets (see TODO above about merging them — https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166#issuecomment-383350378) but if you play both at the same time they should stay in sync.

In https://gltf-viewer.donmccurdy.com/ — 

cc56f558-303c-44e6-9977-59cde24048d5-31999-00001f926d600db7

**Comment by naftalibeder** [comment]
@donmccurdy Thank you for the excellent plugin, it's working great. I've found a bug that I can reproduce in a simple .blend file.

If `Export within playback range` is active, each action receives a new keyframe during export that extends its duration, making all actions longer than they should be. I can't quite figure out what's happening, but it seems like each action gets extended with a single keyframe, and then the next action gets a keyframe-every-frame to match the previous action's new length.

screen shot 2018-05-21 at 4 09 16 pm
screen shot 2018-05-21 at 4 09 40 pm

If `Export within playback range` is inactive, actions export correctly.
[test.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2024089/test.blend.zip)

**Comment by donmccurdy** [comment]
@naftalibeder when exporting only `action-1` with the stable version of this exporter (i.e. make action1 active, then export) do you see the same result? It looks that way to me, but I'm also not sure I understand the image above. If so, let's open a new issue for it.

**Comment by IARI** [comment]
Shape-key animations do not work at all for me, when i load the resulting model in my threejs application or https://github.com/donmccurdy/three-gltf-viewer
For shape-key animations, the scene imported in threejs will contain animationclips with the proper names, but 0 tracks.
What could I be missing?

**Comment by emackey** [comment]
> it doesn't seem to properly open in Blender, the gltf metallic roughness node is gone, and also I cannot add another gltf node, it seems to have vanished from the menu for me.
image

I've seen this happen before, on blend files that were shared with me by a coworker.  In my case what happened here is the blend file was authored with File -> Link... (as the directions here indicate) as opposed to File -> Append... to locate `pbr-node.blend`.  This means that the user's .blend file is looking in a specific place for another separate pbr-node.blend file to link in the contents of the glTF node.  If it doesn't find it at exactly that path, it will quietly fail to load the glTF node, and put that empty placeholder node there instead.

This can happen anytime a blend file is shared to another user or another machine, as the path to pbr-node.blend will be different on the new machine.  I don't know any way to fix this other than to place a copy of the pbr-node.blend file at exactly the path that the main blend file expects it to be.  This can be difficult if the new host machine doesn't have a drive or mount point supporting where the file was found on the other machine.

It's possible to avoid this problem from the start, by always using File->Append instead of Link.  This way a copy of the glTF node gets placed directly in the authored blend file, and the pbr-node.blend file is never needed after that initial import.  Having seen this in the wild now makes me think we should change the user documentation here from Link to Append.

**Comment by IARI** [comment]
@donmccurdy  what still needs to be tested/done such that this PR can be merged?

**Comment by karroffel** [comment]
I'm using the code from this PR in one of my projects and it's working great! One thing I noticed is that if "apply modifiers" is active, the Armature modifier will be applied as well! That means that the pose at export time will be the actual base mesh. This screws all the other animations.

The FBX exporter solves this by setting all armatures to REST position before applying modifiers, then after the export is done it resets them to the original state.

I realize that this issue has been there before and is not specific to this PR, but maybe this would be a good opportunity to fix this issue in this PR since it kind of revamps the Animation export.
If you have multiple animations and a "rest"/"base pose"  animation isn't the only one contributing in the NLA it's *very* easy to get wonky results.

If this is not the right place I'll open a separate issue

**Comment by emackey** [comment]
Thanks great feedback @karroffel, thanks!

**Comment by donmccurdy** [comment]
@IARI does your example fail both with and without the version of the exporter in this PR?

@karroffel this is a fine place to post, but because this PR is taking a while to finish, I think it would be better to start a new issue. Thanks!

**Comment by donmccurdy** [comment]
This PR is ready to merge, if there are no regressions I've missed here. For now the change to current behavior is simple enough: stashed actions and single-strip NLA tracks are written to their own animation clips.

I thought there was a regression with joint matrices, but it's on master as well (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/253). A few other good points have come up in this thread that are not addressed, but I don't think they need to block this PR. Please open new issues for any further improvements we can make here.

**Comment by IARI** [comment]
@donmccurdy you earlier asked "does your example fail both with and without the version of the exporter in this PR?" - sorry for replying thsi late: 
in short: I think the problem is not specific to this PR.

long: I'm not 100% sure, but think this is related to Blender not being able to apply modifiers on objects that have shape keys in general. I think theres no trivial solution to this anyways.

**Comment by emackey** [comment]
@donmccurdy I'm seeing a validation error:

> Animation channel has the same target as channel 1.

Test file:  [ParentingTests_animated.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2185947/ParentingTests_animated.zip)

There's another error here too, unrelated to this branch, in that parenting some objects and exporting with "Selected objects only" causes some meshes & nodes to be exported multiple times, resulting in `This object may be unused` messages.  I haven't nailed that one down yet so I don't know if that's related to the multiple animation targets error.  The animation targets error does seem to be local to this branch though.

**Comment by emackey** [comment]
@donmccurdy I found the root cause.  Don't waste any of your cycles on the problem I posted, it's not local to this branch and I will have a fix that's completely separate from this.

**Comment by IARI** [comment]
Wohoo! :D thanks for merging this, I now am one happy developer ;)

**Pull request merged**
