### PR TITLE
Add area lights to PBR lights extension

### PR DESCRIPTION
**Pull request by tehbelinda**
- includes a new node tree group that can be imported/appended in for area light
- still undecided on unit conversion for light strength

Related issue: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/136

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks — this is a good idea we should consider, but I think it will need to be discussed in the glTF repository, so we can't accept a PR just yet.. See comments in https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/136.

**Comment by tehbelinda** [comment]
Yep no worries, I'll add my notes there

**Comment by UX3D-nopper** [comment]
Suggest, we put area lights to advanced lighting.
Also, hemisphere lights can be implemented using a special environment map.

**Comment by donmccurdy** [comment]
Thanks for writing this up — at this time we can't merge it as we do need to match the `KHR_lights` extension definition. Per comment in https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/136 feel free to leave feedback on the glTF repository encouraging inclusion of area lights in the future, or anyone is welcome to define a "vendor" extension which we could consider adding support for here: it just needs to be separated correctly from `KHR_lights`.

**Comment by donmccurdy** [comment]
Closing as this has gotten outdated, but see https://github.com/KhronosGroup/glTF/pull/1223 for progress on lights in glTF. After that, IBL is the likely next step. Thanks!

**Pull request closed without merging**
