### PR TITLE
Allow JPEG output.

### LINKED ISSUE #124: Option to export as textures in JPEG format
Currently, it appears that image export is [hardcoded to use PNG format](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scripts/addons/io_scene_gltf2/gltf2_generate.py#L2030-L2051). It could be a nice enhancement to offer a choice of texture format, starting with PNG and JPEG, and later offering KHR_texture_compression.

The advantage for JPEG would be smaller filesize and faster transmission for WebGL-based applications.

Related:
- https://stackoverflow.com/questions/10777782/for-opengl-webgl-is-png-or-jpeg-the-most-suitable-file-format
- https://docs.blender.org/manual/en/dev/data_system/files/media/image_formats.html

### LINKED ISSUE #171: request: disable image export
GLTF2 exporter 
writes images to directory. 
I am missing an option to disable this slow feature.

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #124 (export to JPEG), and ~~with some more changes also~~ fixes #171 (don't rewrite identical images). There is no UI option for output format, and I didn't use render output format, since per-texture control seems preferable. Instead:

* In **Blender Render** mode, textures marked with *Use Alpha* are exported as PNG, else JPEG.
* In **Cycles Render** mode, textures used in an Image Texture node with linked *Alpha* socket are exported as PNG, else JPEG.

Leaving this PR open until I get #171 figured out...

/cc @emackey

### CODE REVIEW

**Comment by punkoffice** [comment]
I tried the new release.  I enabled "Enable experimental glTF export settings" in user prefs.  With my texture, under "Image Sampling" I made sure there's no checkmark next to "Alpha : use".  My GLB ends up 7,467KB.  If I turn on Alpha its still 7,467KB.  However, if I convert to FBX first then use the Facebook FBX2glTF converter the GLB file is 1.27MB.  I tried this with another 3D model and the result was the same

**Comment by donmccurdy** [comment]
You’ve used this ZIP: https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1854303/io_scene_gltf2.zip (from #124) correct? Could you try exporting to .gltf to verify it is actually creating a .jpeg when alpha is off??

**Comment by punkoffice** [comment]
Yep, I just tried that one you linked, converted to glTF and the result is always a .PNG.  Doesn't matter if I have alpha enabled or disabled.

**Comment by donmccurdy** [comment]
Oops, this is the the checkbox i meant:

use_alpha

Very possibly this change should use both for less confusion, or maybe *Influence > Alpha* is the key thing... Anyway the basics are here. 😅

**Comment by punkoffice** [comment]
I don't have that "Use Alpha" option for my texture because the texture is JPG.  "Use Alpha" will only appear if its a PNG

**Comment by donmccurdy** [comment]
Ah, and apparently it defaults to “true” when it’s hidden? 😩 In that case i’ll definitely use a different checkbox, thanks.

**Comment by punkoffice** [comment]
All good!  I'm wondering, if the original texture is a JPG shouldn't it just default to JPG?  Is there any reason to convert a JPG to PNG?

**Comment by donmccurdy** [comment]
Here's a new version:

[io_scene_gltf2.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1888326/io_scene_gltf2.zip)

Summary:
- By default, write to JPEG.
- If any of the following are true, switch to PNG:
  - `Color Space > Use Alpha` is checked
  - `Influence > Diffuse > Alpha` is checked
  -  Using *Cycles Render* mode, and texture is used in an Image Texture node with linked Alpha socket
- If file format doesn't need to be changed, copies the file rather than re-rendering.

**Comment by donmccurdy** [comment]
>  I'm wondering, if the original texture is a JPG shouldn't it just default to JPG?

No specific reason not to, but in the end the code seems simpler with the criteria above.

**Comment by punkoffice** [comment]
[abby.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1911538/abby.zip)
No worries.  There is the .FBX and .JPG diffuse texture in there

**Comment by donmccurdy** [comment]
@punkoffice try exporting to plain `.gltf` to verify the image comes out as a JPG instead of PNG. When I tried importing the FBX file here, the *Use Alpha* checkbox above was somehow checked, resulting in both incorrect render in Blender and a much larger PNG export.

After unchecking that, I'm getting export sizes of 1.4 MB for `.gltf` and 1.0 MB for `.glb`. Also note that since this is merged, the most recent version of the exporter would be downloaded from the main project download link.

**Comment by punkoffice** [comment]
I don't know why but I can't get it to export .JPG.  I'm exporting to GLTF and it always comes out as PNG.  I've downloaded the latest addon with the merged changes from here https://github.com/KhronosGroup/glTF-Blender-Exporter/archive/master.zip  I imported the .FBX file.  I did notice Use Alpha was checked so I unchecked it.   Transparency is not checked.  Show Alpha and Use Alpha is not checked.  Alpha influence is not checked.  I have "enable experimental glTF export settings" enabled.  I'm using Blender 2.79

**Comment by donmccurdy** [comment]
Hm, could you post the `.blend` file too I guess then? Also note that you have to restart Blender after updating an extension.

**Comment by punkoffice** [comment]
[test_addon.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1911696/test_addon.zip)
Ok, I did restart but it made no difference.  I've attached the .blend file in the ZIP.  Btw, thank you for your patience

**Comment by donmccurdy** [comment]
@punkoffice OK, I've updated this with https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/504a5254e527bdc0aa8abc21875dc4a1fca7d153 and I think it's fixed now. Apparently `image.use_alpha` can be true for JPG files, and the option in the UI gets hidden so there's no way to uncheck it.

**Comment by donmccurdy** [comment]
So now the only way to cause a PNG to be exported, with Blender Render, should be using the Influences tab:

screen shot 2018-04-15 at 12 14 36 pm

**Pull request merged**
